### ISSUE TITLE
Dealer cheats with handsaw

### ISSUE THREAD

**Issue by MSLaFaver** [ITR13/BuckshotRouletteMods#1]
I found a bug while playing the mod myself and while watching Delightful Kissboy’s video. The Dealer is allowed to saw off the gun and shoot himself with a blank, keeping the sawed gun. If the player does this, the gun grows back. This appears to be a bug with the base game, but it never happens because the original Dealer sucks. This should probably be changed so that he waits until his next shot is at the player before deciding to use the hacksaw.

**Comment by ITR13** [comment]
Might consider it for v1.0.2

**Comment by ScientificGuy** [comment]
Does this fix stop the Dealer from using the handsaw if he knows he’s going to shoot himself? I see that the fix was implemented that he doesn’t shoot himself if he’s used the handsaw, but wouldn’t that just mean he shoots the player, leading to a wasted turn?
