### ISSUE TITLE
SmarterDealer: Inverter problems

### ISSUE THREAD

**Issue by Voenkomat1488** [ITR13/BuckshotRouletteMods#10]
### This happened in Double or Nothing mode, round two 

Round data:
- 4 blank rounds
- 4 live rounds

My Items:
- Spoilt medicine
- Inverter (2)
- Beer
 
Dealer's items:
- Handcuffs
- Adrenaline (2)
- Beer

I successfully shot the Dealler, however his next move confused me

**He used andrenaline to take the inverter from me, thus making the round real, however after that he skipped it with beer. It's not clear what exactly he was trying to do with this move, as:**

1. The current bullet is unknown to him
2. Not much justification for the risk of changing it, but still, it doesn't make sense to skip an already changed round
3. Even if Diller was assuming the bullet would be the real one, why wouldn't he shoot me?

_Presumably the Dealer is somehow misunderstanding the functionality of the inverter)_

I'm attaching the video proof, if anything there is a longer version at the link below, it's unlikely I'll be able to upload it to Github
(The video quality on Github is intentionally reduced in favour of smaller size and limitations)

https://gemoo.com/tools/upload-video/share/643657183676186624?codeId=DWlXdO4ZErLoL&card=643657180220080128&origin=videohosting

P.S
**I like very much what you are doing, your mod and the endeavour to make the dealer intelligence perfect. Please don't take offence to me, I'm just reporting bugs I've noticed to help for future development, not criticising in any way!!!!**

**Keep up the good work!**

https://github.com/ITR13/BuckshotRouletteMods/assets/72986030/191bdd0c-e305-4b39-807e-cccae39fff81

**Comment by ITR13** [comment]
Thanks! This slipped by me. I'll don't have time to take a look in the nearest future, but I'll try to find time sometime.
