### ISSUE TITLE
[ShellDisplay] add colorblind support

### ISSUE THREAD

**Issue by h3oCharles** [ITR13/BuckshotRouletteMods#11]
if colorblind support is enabled in settings, the shell display mod doesn't respect that
idk where to write this issue but that mod is there in releases so ergh

**Comment by ITR13** [comment]
Hmm, yeah, it just uses a acreenshot of the bullets. I could try taking a pic of the colorblind bullets and replacing them if colorblind mode is on?

What differences are there? Since they're always in the same position I could also just add text next to the bullets

**Comment by h3oCharles** [comment]
the difference is just the color - white is live, black is blank
