### ISSUE TITLE
[ShellDisplay] display appears after play

### ISSUE THREAD

**Issue by h3oCharles** [ITR13/BuckshotRouletteMods#12]
after winning a set of Double of Nothing and rejecting the offer, I had 1 live remaining, which was still appearing during the outro, and also during the splash screen and main menu

![image](https://github.com/ITR13/BuckshotRouletteMods/assets/8020330/b0933f4d-31bf-4b9b-b4c2-44c2b6193b98)

**Comment by ITR13** [comment]
I had a fix for this at one point, but it involved touching more files

**Comment by ITR13** [comment]
Fixed it so it won't show up in main menu or death scenes anymore, but it probably still appears on the end screen.
