### ISSUE TITLE
Dealer shot himself

### ISSUE THREAD

**Issue by MSLaFaver** [ITR13/BuckshotRouletteMods#2]
Round 1, loadout 1, 1 live shell, 2 blank shells. I have magnifying glass, Dealer has hacksaw. I shoot Dealer, blank. Dealer immediately shoots himself, live. Don't see a reason for this to happen.

Edit: This happened again when he had the hacksaw and there was 1 live and 1 blank in the chamber.

**Comment by ITR13** [comment]
Didn't see this, but might've been because of #5, or might've been fixed in the update that had that issue. Do tell me if you see this again
