### ISSUE TITLE
Mod doesnt work

### ISSUE THREAD

**Issue by AlneXo** [ITR13/BuckshotRouletteMods#6]
i downloaded latest version of mod and latest mod loader
when i threw it into the mods folder and launch BS, it just crashes
(other mods work normally)

**Comment by victorblino** [comment]
you need download the pre-release modloader. i had the same problem haha - [modloader prerelease](https://github.com/AGO061/BuckshotRouletteModLoader/releases/tag/1.1.0-prerelease.1)
