### ISSUE TITLE
Smarter Dealer: The dealer used the inverter before the magnifying glass.

### ISSUE THREAD

**Issue by Voenkomat1488** [ITR13/BuckshotRouletteMods#9]
Unfortunately it was not possible to capture, however I'd better record gameplay in the future)

The dealer already had a magnifying glass, but for some strange reason decided to use the inverter first (unknowingly turned a live shell into a blank), then used the glass, found out that the shell is blank, and shot himself.

To me it's objectively a pointless waste of two items, he could have just shot at me using the glass

Fix it if possible please)

**Comment by ITR13** [comment]
Do you remember how many items the dealer had, and if it was a double or nothing round? It might have tried to get rid of some items so it can pick up new ones (though, with inverter this is unlikely), or seen that it would die/win no matter what.
